// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

import frc.robot.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.GenericHID.RumbleType;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public JoystickButton joystickButton2;
public Joystick driveGamepad;
public JoystickButton joystickButton5;
public JoystickButton driveForwardTest;
public JoystickButton joystickButton4;
public JoystickButton joystickButton6;
public JoystickButton joystickButton3;
public JoystickButton joystickButton1;
public JoystickButton joystickButton7;
public Joystick operatorGamepad;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

operatorGamepad = new Joystick(1);

joystickButton7 = new JoystickButton(operatorGamepad, 6);
joystickButton7.whileHeld(new TurnToGyroAngle(90));
joystickButton1 = new JoystickButton(operatorGamepad, 1);
joystickButton1.whileHeld(new Shoot());
joystickButton3 = new JoystickButton(operatorGamepad, 3);
joystickButton3.whenPressed(new driveForFeet(-3));
joystickButton6 = new JoystickButton(operatorGamepad, 7);
joystickButton6.whenPressed(new turnPlusGyroValue(-360));
joystickButton4 = new JoystickButton(operatorGamepad, 8);
joystickButton4.whenPressed(new turnPlusGyroValue(90));
driveForwardTest = new JoystickButton(operatorGamepad, 4);
driveForwardTest.whenPressed(new driveForFeet(15));
joystickButton5 = new JoystickButton(operatorGamepad, 1);
joystickButton5.whileHeld(new Run_Intake());
driveGamepad = new Joystick(0);

joystickButton2 = new JoystickButton(driveGamepad, 2);
joystickButton2.whileHeld(new AutoAlign());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("XDrive", new XDrive());
        SmartDashboard.putData("Shoot", new Shoot());
        SmartDashboard.putData("ShootWithPID", new ShootWithPID());
        SmartDashboard.putData("Run_Intake", new Run_Intake());
        SmartDashboard.putData("Do_Climb", new Do_Climb());
        SmartDashboard.putData("StopShooter", new StopShooter());
        SmartDashboard.putData("AutoAlign", new AutoAlign());
        SmartDashboard.putData("RumbleDrive", new RumbleDrive());
        SmartDashboard.putData("RumbleOperator", new RumbleOperator());
        SmartDashboard.putData("setRumble", new setRumble());
        SmartDashboard.putData("stopRumble", new stopRumble());
        SmartDashboard.putData("Run_Indexer", new Run_Indexer());
        SmartDashboard.putData("passAutoLine", new passAutoLine());
        SmartDashboard.putData("SixBallAutoLT", new SixBallAutoLT());
        SmartDashboard.putData("TargetPosAuto", new TargetPosAuto());
        SmartDashboard.putData("SixBallAutoRT", new SixBallAutoRT());
        SmartDashboard.putData("DoNothingFor_AutoCommand", new DoNothingFor_AutoCommand());
        SmartDashboard.putData("UniversalShootAuto", new UniversalShootAuto());
        SmartDashboard.putData("shootAtRPM", new shootAtRPM());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
public Joystick getdriveGamepad() {
        return driveGamepad;
    }

public Joystick getoperatorGamepad() {
        return operatorGamepad;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public void setDriveRumble(double left, double right){
        driveGamepad.setRumble(RumbleType.kLeftRumble, left);
        driveGamepad.setRumble(RumbleType.kRightRumble, right);
    }

    public void setOperatorRumble(double left, double right){
        operatorGamepad.setRumble(RumbleType.kLeftRumble, left);
        operatorGamepad.setRumble(RumbleType.kRightRumble, right);
    }
}

