// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import com.ctre.phoenix.CANifier.LEDChannel;

import edu.wpi.first.wpilibj.command.Command;
import frc.robot.Robot;
import frc.robot.commands.*;
import frc.robot.subsystems.Limelight.CamMode;
import frc.robot.subsystems.Limelight.LEDMode;

/**
 *
 */
public class AutoAlign extends Command {
    public double x;
    public double absX;
    private int count;
    // public final double kP = 0;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutoAlign() {

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        Robot.limelight.setLight(LEDMode.ON);
        Robot.limelight.setCameraMode(CamMode.VISION);
        count = 0;
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {        
        if (Robot.limelight.targetInSight()== true){

            x = Robot.limelight.getTargetAngleX();
            absX = Math.abs(x);
            double adjust = (x/29.8)*.25;
            double y = Robot.oi.getdriveGamepad().getRawAxis(1)*.6; //may or may not keep this
            if (absX>.8){
                if (x > 0){
                    //System.out.println(.32+adjust);
                    Robot.drive.arcade(y, .12+adjust,false);
                }else if(x < 0){
                    Robot.drive.arcade(y, -.12+adjust,false);
                    //System.out.println(-.32+adjust);
                }
        }else{
            count++;
            Robot.drive.arcade(y, 0);
            //Robot.oi.setOperatorRumble(.5, .5);
        }
    }else{
        if (Robot.getAuto()){
            //seek
        }else{
            Robot.drive.arcade(Robot.oi.getdriveGamepad().getRawAxis(1)*.7, Robot.oi.getdriveGamepad().getRawAxis(4)*.5);
        }
            
    }
}
        
    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return (count>10);
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.limelight.setLight(LEDMode.OFF);
        Robot.limelight.setCameraMode(CamMode.DRIVER);
        Robot.oi.setOperatorRumble(0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
