// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import frc.robot.subsystems.*;

/**
 *
 */
public class SixBallAutoRendezvous extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public SixBallAutoRendezvous() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
        addSequential(new PrepareBallForShoot(false));
        addParallel(new SetRPMVision());
        addParallel(new Start_Shooter(true));
        addParallel(new Run_Intake(.3));
        addSequential(new AutoAlign(1));
        addSequential(new WaitForShooterSpeed());
        addSequential(new AutomatedShoot());
        addSequential(new AutomatedShoot());
        addSequential(new AutomatedShoot());
        addSequential(new TurnToGyroAngle(0));
        addSequential(new DriveQuick(-.7,.5)); //this is actually forward
        addSequential(new PauseFor(.3));
        addSequential(new driveForFeet(4,.5));
        addSequential(new driveForFeet(1.2,.15));
        addSequential(new TurnToGyroAngle(40));
        addSequential(new driveForFeet(.5,.3));
        addSequential(new TurnToGyroAngle(0));
        //addSequential(new PauseFor(.25));
        addParallel(new Stop_Intake()); //so they fall if jammed
        addSequential(new driveForFeet(-5.5,.8));
        addSequential(new AutoAlign(1));
        addParallel(new Run_Intake(.3));
        addSequential(new WaitForShooterSpeed());
        addSequential(new AutomatedShoot());
        addSequential(new AutomatedShoot());
        addSequential(new AutomatedShoot());
    } 
}
